site_name: Jiazhen's Personal Pages
site_url: https://hokachan2004.github.io/eepages/
site_author: He Jiazhen(何家镇)
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: deep-purple # 上方的
      accent: grey # 链接等可交互元件的高亮色
      # teal
      toggle:
        icon: material/brightness-7 # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      # teal
      toggle:
        icon: material/brightness-4
        name: 切换至日间模式
  features:
    - navigation.tracking
    - navigation.tabs # 顶部导航栏
    - navigation.top # 返回顶部
    - navigation.footers # 页脚
    - search.suggest # 搜索建议
    - search.highlight # 搜索高亮
    - navigation.instant # 即时导航 单网页应用
    - navigation.expand # 导航栏展开
  language: zh

nav:
  - 主页: index.md
  - EE专业课程: 
    - 微电子工艺: micro-process/process.md
    - 操作系统: os/os.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
